#ifndef CONSTANTS_H
#define CONSTANTS_H

#define STATE_MAX 32

enum triggers {
    TRIGGER_CLICK = 0,
    TRIGGER_MOUSEDOWN,
    TRIGGER_MOUSEUP,
    TRIGGER_MOUSEOVER,
    TRIGGER_SUBMIT,
    TRIGGER_ARIA,
    TRIGGER_LINK,
    TRIGGER_INIT
};

enum linkTypes {
    LINK_INTERNAL = 0,
    LINK_RELATIVE,
    LINK_SAME_HOST,
    LINK_EXTERNAL
};

enum arrowTypes {
    ARROW_TYPE_EVENT_CLICK = 0,
    ARROW_TYPE_EVENT_MOUSEDOWN,
    ARROW_TYPE_EVENT_MOUSEUP,
    ARROW_TYPE_EVENT_MOUSEOVER,
    ARROW_TYPE_EVENT_SUBMIT,
    ARROW_TYPE_EVENT_ARIA,
    ARROW_TYPE_LINK_EXTERNAL,
    ARROW_TYPE_LINK_SAME_HOST,
    ARROW_TYPE_LINK_FRAGMENT,
    ARROW_TYPE_ACTION,
    ARROW_TYPE_INIT
};

enum arrowFlags {
    ARROW_FLAG_VISIBLE = 1,
    ARROW_FLAG_EVENT = 2,
    ARROW_FLAG_LINK = 4,
    ARROW_FLAG_ARIA = 8
};

#endif // CONSTANTS_H
